### ISSUE TITLE
https://status.slack.com/ suffers from missing background

### ISSUE THREAD

**Issue by neico** [laCour/slack-night-mode#27]
Either exclude main pages from the style or consider going over them and see if there's more of such cases

![](http://puu.sh/lr8G9/ffcb728655.png)

**Comment by laCour** [comment]
Until recently, the theme had styles so that it wouldn't affect this page, but I [removed them](https://github.com/laCour/slack-night-mode/commit/65250293ccee22b90671cb80a3cb733411bf4d45) since it's been pushing up against the Userstyle's 100KB limit.

The owner has lifted that limit for the theme, so I can properly do this now. Slack has added some identifying classes which weren't there previously, so that I can actually properly style the page.

I'll get around to this hopefully this weekend. Thanks!

**Comment by laCour** [comment]
I haven't forgotten about this, I just haven't had the time to style this. It will be included in the next release, the recent release fixed some small important bugs.
