### ISSUE TITLE
Highlighting on channel message about exceeding message limit

### ISSUE THREAD

**Issue by shmup** [laCour/slack-night-mode#44]
When you bring a channel into focus and it has the inline message telling you that your message limited has exceeded the "free account" limit, it has an initial highlight/background color of some very displeasing colors. Seconds later the highlight leaves and it is fine.

I wish I had snagged a screenshot in time, and now I can barely remember the colors specifically enough to explain. Well they're related to the theme anyways, but we need default settings.

**Comment by laCour** [comment]
Thanks! I've released a fix for this. You should be able to update, providing caches have updated. Let me know if this has fixed the issue for you.

Slack does this animation with JavaScript, and the background seems to collide with day dividers. So for now I've forcefully removed the background flashing so that it's not such an eyesore.
