### ISSUE TITLE
Unread channel color white

### ISSUE THREAD

**Issue by exstral** [laCour/slack-night-mode#79]
Love the theme! Would it be possible to have the unread channel text be completely white (#000) in addition to heavy, so they are a little bit easier to tell apart form all the other channels? :)

**Comment by terminalmage** [comment]
Actually, the unread channels (up until a couple days ago) were a shade of grey, which offered much better contrast. The unread channels changed to white after the recent update.

It would probably be better to just change the unread channels back to their previous color.

**Comment by laCour** [comment]
An update has been released which fixes this, let me know if this works.

**Comment by terminalmage** [comment]
I just updated via userstyles.org (Stylish's built-in updater always seems to lag behind in terms of updates), but I notice no change in the color of the read channels, they are still white instead of grey. It's Sunday though and no one is on either of the Slack teams I use, and I have no unread channels. So, I'll have to keep an eye on it and see what the unread color ends up being.

**Comment by laCour** [comment]
Ah, I misread. I didn't realize these were previously a different shade. I've released another update which improves the contrast.

**Comment by terminalmage** [comment]
I just installed the update and can confirm the channels with no new messages are using a darker shade, which should provide plenty of contrast between the white used for channels with unread messages.

Thanks!
