### ISSUE TITLE
Slack update broke some things

### ISSUE THREAD

**Issue by ghost** [laCour/slack-night-mode#93]
See attached photo, as the menu on the left has discoloured font for channels without unread messages.

http://imgur.com/a/82U7l

**Comment by laCour** [comment]
I'm not able to replicate this issue, can you verify that you've updated to the latest version by updating via userstyles.org: https://userstyles.org/styles/101971/slack-night-mode

**Comment by ghost** [comment]
http://imgur.com/a/J5wme

**Comment by laCour** [comment]
@connordelan You'll specifically want to update via the userstyles.org website, not through the Stylish extension. The extension has problems with updating. Let me know if this works.

**Comment by ghost** [comment]
I have removed the style numerous times and re-installed, it changes nothing.

**Comment by laCour** [comment]
Please confirm that this isn't caused by your selected slack sidebar theme.

If not, click the _Edit_ button for the style on the Stylish extension page. On the left sidebar, click on _Import_ under Mozilla Format. Paste the contents of this: https://raw.githubusercontent.com/laCour/slack-night-mode/master/css/variants/aubergine.css

Then click _Overwrite Style_. Does this change anything?
